[workspace]
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "croppy"
platforms = ["osx-64", "osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
croppy = "python -m croppy"
test = "pytest"

[dependencies]
python = "3.12.*"
pyside6 = ">=6.7"
typer = ">=0.12"
loguru = ">=0.7"
ffmpeg = ">=6"

[pypi-dependencies]
croppy = { path = ".", editable = true }

[feature.dev.dependencies]
pytest = ">=8"
pytest-qt = ">=4"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
