"""Shared test fixtures."""

from __future__ import annotations

import faulthandler
import os
import subprocess
from pathlib import Path

import pytest
from PySide6.QtCore import QCoreApplication, QSettings

from croppy.ffmpeg.binary import find_ffmpeg


def pytest_configure(config: pytest.Config) -> None:
    """Arm a deadlock watchdog when ``CROPPY_TEST_WATCHDOG_SECS`` is set.

    The suite has hung at *shutdown* on CI (a background thread-pool task
    outliving the tests can block the pool's no-timeout destructor forever). If
    the process is still alive this many seconds after start, dump every thread's
    stack to stderr and hard-exit — turning a multi-hour CI hang into a fast,
    diagnosable failure. Off by default so local runs are unaffected.
    """
    secs = os.environ.get("CROPPY_TEST_WATCHDOG_SECS")
    if secs and int(secs) > 0:
        faulthandler.enable()
        faulthandler.dump_traceback_later(int(secs), exit=True)


@pytest.fixture(autouse=True)
def _isolate_qsettings(tmp_path: Path) -> None:
    """Redirect QSettings to a per-test temp dir so persistence tests never
    read or clobber the real user configuration."""
    QCoreApplication.setOrganizationName("croppy-test")
    QCoreApplication.setApplicationName("croppy-test")
    QSettings.setDefaultFormat(QSettings.Format.IniFormat)
    QSettings.setPath(
        QSettings.Format.IniFormat,
        QSettings.Scope.UserScope,
        str(tmp_path),
    )


@pytest.fixture(autouse=True)
def _drain_media_loaders():
    """Wait for any background MediaLoader work to finish at the end of each test.

    Several widget tests kick off async probe/frame-extraction and assert
    synchronously without awaiting it. Left running, that work outlives the test
    and can be garbage-collected mid-event-loop in a later test — a hard
    segfault on macOS. Draining here keeps background work inside its own test.
    """
    yield
    from croppy.gui.media_loader import MediaLoader

    MediaLoader.drain_all()
    app = QCoreApplication.instance()
    if app is not None:
        app.processEvents()  # deliver any pending result callbacks while widgets live


@pytest.fixture(scope="session")
def test_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A tiny synthetic mp4 generated by ffmpeg's lavfi testsrc.

    320x240, 30 fps, 2 seconds, H.264 + yuv420p. Generated once per test session.
    """
    out = tmp_path_factory.mktemp("media") / "testsrc.mp4"
    cmd = [
        str(find_ffmpeg()),
        "-y",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc=size=320x240:rate=30:duration=2",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        str(out),
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out
