"""Shared test fixtures."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from croppy.ffmpeg.binary import find_ffmpeg


@pytest.fixture(scope="session")
def test_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A tiny synthetic mp4 generated by ffmpeg's lavfi testsrc.

    320x240, 30 fps, 2 seconds, H.264 + yuv420p. Generated once per test session.
    """
    out = tmp_path_factory.mktemp("media") / "testsrc.mp4"
    cmd = [
        str(find_ffmpeg()),
        "-y",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc=size=320x240:rate=30:duration=2",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        str(out),
    ]
    subprocess.run(cmd, check=True, capture_output=True)
    return out
